---

- hosts: all
  become: true
  pre_tasks:  

  - name: Update System(Red Hat)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: Update System(Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Update System(Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"


- hosts: web_servers
  become: true
  tags: apache2, ubuntu
  tasks:
  - name: Install apache and php (Ubuntu)
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: db_servers
  become: true
  tags: db, mariadb, redhat
  tasks:
  - name: Install MariaDB (RedHat)
    dnf:
      name: mariadb 
      state: latest 
    when: ansible_distribution == "RedHat"


- hosts: file_servers
  become: true
  tags: fs, samba, debian
  tasks:
  - name: Install Samba (Debian)
    package:
      name: samba 
      state: latest 
    when: ansible_distribution == "Debian"
  