---
- hosts: all
  become: true
  name: Cache Update
  pre_tasks:
    - name: Update Repo Cache(For all)
      tags: always
      ansible.builtin.package:
        update_cache: true
      changed_when: false

- hosts: all
  become: true
  name: User Creation
  roles:
    - base

- hosts: web_servers
  name: Web Server Setup
  become: true
  roles:
    - web_servers

- hosts: db_servers
  name: Database Server Setup
  become: true
  roles:
    - db_servers

- hosts: file_servers
  name: File Server Setup
  become: true
  roles:
    - file_servers